import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ToastContainerBar from "@/provider/ToastContainerBar";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import getCurrentUser from "./actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Online Booking Reservation App",
  description: "Generated by create next app",
  icons:
    "https://p7.hiclipart.com/preview/893/122/385/travel-agent-trip-planner-logo-travel.jpg",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={"bg-neutral-200" + inter.className}>
        <Navbar currentUser={currentUser} />
        <ToastContainerBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
